/* Information-gap speaking task. No roster or dialogue is sent to a server. */
(() => {
  const animals = [
    {name:'Giant panda',found:'central China',diet:'bamboo',behavior:'resting in bamboo forests',threat:'habitat loss',protection:'conservation programs',fact:'spending much of its day eating bamboo'},
    {name:'Polar bear',found:'the Arctic',diet:'seals',behavior:'walking on sea ice',threat:'shrinking sea ice',protection:'wildlife laws',fact:'swimming long distances'},
    {name:'Sea turtle',found:'warm oceans around the world',diet:'sea grass and small sea animals',behavior:'swimming near coral reefs',threat:'plastic waste and fishing nets',protection:'wildlife laws',fact:'returning to a beach to lay eggs'},
    {name:'Pangolin',found:'parts of Africa and Asia',diet:'ants and termites',behavior:'rolling into a ball when threatened',threat:'illegal hunting',hunted:'its scales',protection:'wildlife laws',fact:'having hard scales'},
    {name:'Elephant',found:'parts of Africa',diet:'grass, leaves, and fruit',behavior:'moving in family groups',threat:'habitat loss and illegal hunting',hunted:'its ivory',protection:'wildlife laws and park rangers',fact:'using its trunk to pick up food'},
    {name:'Tiger',found:'parts of Asia',diet:'deer and other animals',behavior:'walking alone through forests',threat:'habitat loss and illegal hunting',hunted:'its skin and bones',protection:'wildlife laws and park rangers',fact:'having a different stripe pattern from every other tiger'},
    {name:'Blue whale',found:'oceans around the world',diet:'tiny animals called krill',behavior:'swimming through deep water',threat:'ship strikes and fishing gear',protection:'international laws',fact:'being the largest animal on Earth'},
    {name:'Orangutan',found:'the rainforests of Borneo and Sumatra',diet:'fruit and leaves',behavior:'climbing trees',threat:'forest loss',protection:'conservation groups',fact:'building a new nest to rest in'},
    {name:'Koala',found:'eastern Australia',diet:'eucalyptus leaves',behavior:'resting in eucalyptus trees',threat:'habitat loss and wildfires',protection:'wildlife rescue teams',fact:'sleeping for many hours each day'},
    {name:'Snow leopard',found:'high mountains in Central Asia',diet:'wild sheep and other animals',behavior:'moving quietly across rocky slopes',threat:'habitat loss and illegal hunting',protection:'wildlife laws',fact:'using its long tail for balance'},
    {name:'Rhino',found:'parts of Africa and Asia',diet:'grass and leaves',behavior:'walking across grasslands',threat:'illegal hunting',hunted:'its horn',protection:'wildlife guards',fact:'having thick skin and a strong horn'},
    {name:'Sea otter',found:'coastal waters of the North Pacific',diet:'shellfish and sea urchins',behavior:'floating on its back',threat:'oil spills and pollution',protection:'marine conservation laws',fact:'using rocks to open hard shells'}
  ];
  const prompts = [
    ['Do you know','where this animal is found','?'],['Can you tell me','what it is called','?'],
    ['Do you know','how it is protected','?'],['I wonder','why it is hunted','.'],
    ['Do you know','what it eats','?'],['Can you tell me','how it survives in the wild','?'],
    ['Do you know','why it is endangered','?'],['I wonder','how it protects itself','.']
  ];
  const passiveChoices=['is found','is called','is hunted','is protected','is threatened','is known for'];
  const state={index:Math.floor(Math.random()*animals.length),view:'reporter',pending:'expert',turns:[],selectedQuestion:0,selectedAnswer:0,guess:'',revealed:false,reflectionQuestions:new Set(),reflectionPassive:new Set(),nameRevealed:false,factsRevealed:false,sampleOpen:false,framesLarge:false,roster:'',pair:'',seconds:180,running:false};
  let tick=null;
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const current=()=>animals[state.index];
  const answerList=a=>[
    `It is found in ${a.found}.`, `It is called a ${a.name.toLowerCase()}.`,
    `It is known for eating ${a.diet}.`, `It is often seen ${a.behavior}.`,
    a.hunted?`It is hunted for ${a.hunted}.`:`It is threatened by ${a.threat}.`,
    `It is protected by ${a.protection}.`, `It is known for ${a.fact}.`,
    'It can be protected by keeping its habitat safe.'
  ];
  const timeText=()=>`${String(Math.floor(state.seconds/60)).padStart(2,'0')}:${String(state.seconds%60).padStart(2,'0')}`;
  const art=()=>`<div class="mystery-art quadrant-${state.index%4}" role="img" aria-label="Mystery animal illustration" style="background-image:url('assets/mystery-animals/set-${Math.floor(state.index/4)+1}.png')"></div>`;
  const timer=()=>`<div class="timer-card" aria-live="off"><span>3-MINUTE CHALLENGE</span><strong class="news-timer">${timeText()}</strong></div>`;
  function switchTo(role){state.pending=role;state.view='transition';window.render()}
  function reset(pick=state.index){state.index=pick;state.view='reporter';state.pending='expert';state.turns=[];state.selectedQuestion=0;state.selectedAnswer=0;state.guess='';state.revealed=false;state.reflectionQuestions.clear();state.reflectionPassive.clear();state.nameRevealed=false;state.factsRevealed=false;state.sampleOpen=false;state.seconds=180;state.running=false;clearInterval(tick);tick=null;window.render()}
  function logTurn(role){if(state.view!==role||state.turns.length%2!==(role==='reporter'?0:1))return;const text=role==='reporter'?prompts[state.selectedQuestion].join(' '):answerList(current())[state.selectedAnswer];state.turns.push({role,text});switchTo(role==='reporter'?'expert':'reporter')}
  function startTimer(){if(state.running)return;if(state.seconds===0)state.seconds=180;state.running=true;tick=setInterval(()=>{state.seconds=Math.max(0,state.seconds-1);document.querySelectorAll('.news-timer').forEach(el=>el.textContent=timeText());if(state.seconds===0){clearInterval(tick);tick=null;state.running=false}},1000);window.render()}
  const frame=(p,i)=>`<button class="question-frame ${state.selectedQuestion===i?'selected':''}" data-news="question" data-i="${i}" aria-pressed="${state.selectedQuestion===i}"><span class="starter">${esc(p[0])}</span><span class="clause">${esc(p[1])}</span><span>${p[2]}</span></button>`;
  function teacherPanel(){return `<aside class="news-teacher"><p class="overline">TEACHER CONTROLS</p><div class="news-actions"><button class="action-btn" data-news="random">🎲 Random Animal</button><button class="action-btn secondary" data-news="next">Next Animal →</button><button class="action-btn secondary" data-news="toggle-name">${state.nameRevealed?'Hide':'Reveal'} Animal Name</button><button class="action-btn secondary" data-news="toggle-facts">${state.factsRevealed?'Hide':'Reveal'} Expert Information</button><button class="action-btn secondary" data-news="toggle-sample">${state.sampleOpen?'Hide':'Reveal'} Sample Dialogue</button><button class="action-btn secondary" data-news="reset">Reset Dialogue</button><button class="action-btn secondary" data-news="large">${state.framesLarge?'Normal':'Enlarge'} Question Frames</button><button class="action-btn blue" data-news="timer">⏱ Start 3-Minute Challenge</button></div><div class="roster"><label for="rosterInput">Student names (comma or line separated; only kept in this tab)</label><textarea id="rosterInput" rows="2" placeholder="Enter at least two names">${esc(state.roster)}</textarea><button class="action-btn secondary" data-news="pair">👥 Random Pair</button><strong class="pair-result" aria-live="polite">${esc(state.pair)}</strong></div><p class="micro">Suggested time: 3 minutes. Listen for wh- + subject + verb and be + p.p.; each partner should speak at least three times.</p></aside>`}
  function sampleDialogue(a){let lines=[['Reporter',prompts[0]],['Expert',answerList(a)[0]],['Reporter',prompts[4]],['Expert',answerList(a)[2]],['Reporter',prompts[3]],['Expert',answerList(a)[4]],['Reporter',prompts[2]],['Expert',answerList(a)[5]],['Reporter',`Hmm... Is it a ${a.name.toLowerCase()}?`],['Expert','Yes, it is!']];return `<details class="sample-dialogue" ${state.sampleOpen?'open':''}><summary>Sample Dialogue · 示範對話</summary><div>${lines.map(([role,line])=>`<p><b>${role}:</b> ${Array.isArray(line)?`<span class="sample-starter">${esc(line[0])}</span> <span class="sample-clause">${esc(line[1])}</span>${line[2]}`:`<span class="sample-passive">${esc(line)}</span>`}</p>`).join('')}</div></details>`}
  function reflection(){return `<section class="card detective"><p class="overline">🔎 LANGUAGE DETECTIVE</p><h3>Which expressions did you use or hear?</h3><p>Click the expressions you used in your conversation.</p><div class="detective-grid"><div><strong>Embedded questions</strong><div class="detective-options">${[prompts[0][1],prompts[1][1],prompts[3][1],prompts[2][1],prompts[4][1],prompts[6][1]].map((x,i)=>`<button data-news="reflect-q" data-i="${i}" aria-pressed="${state.reflectionQuestions.has(i)}">${esc(x)}</button>`).join('')}</div></div><div><strong>Passive voice</strong><div class="detective-options">${passiveChoices.map((x,i)=>`<button data-news="reflect-p" data-i="${i}" aria-pressed="${state.reflectionPassive.has(i)}">${esc(x)}</button>`).join('')}</div></div></div><p class="reflection-result" aria-live="polite">Great! You used <b>${state.reflectionQuestions.size}</b> embedded questions and <b>${state.reflectionPassive.size}</b> passive-voice expressions.</p></section>`}
  function reporter(a,projector=false){
    const expected=state.turns.length%2===0;
    const teacherName=!projector&&state.nameRevealed&&window.teacher?`<p class="teacher-secret">Teacher reveal: <b>${esc(a.name)}</b></p>`:'';
    const teacherFacts=!projector&&state.factsRevealed&&window.teacher?`<section class="card teacher-secret"><h3>Teacher reveal · Expert information</h3>${factList(a)}</section>`:'';
    const after=projector?'':`${teacherFacts}${state.turns.length>=6?guessPanel(a):'<div class="news-progress">Complete at least 6 speaking turns (3 questions + 3 answers) to unlock your guess.</div>'}${state.revealed?reflection():''}`;
    return `<div class="news-layout"><section class="card news-visual reporter-visual"><span class="role-pill reporter-pill">STUDENT A · REPORTER</span>${art()}<p class="mystery-caption">MYSTERY ANIMAL · Ask for clues before you guess.</p>${teacherName}</section><section class="card role-card reporter-card"><div class="role-heading"><div><p class="overline">ASK · DISCOVER · REPORT</p><h3>Ask your Wildlife Expert</h3></div>${timer()}</div><p class="micro">Choose a frame, ask it aloud, then record your speaking turn. The expert has the secret card.</p><div class="question-frames ${state.framesLarge?'frames-large':''}">${prompts.map(frame).join('')}</div><div class="turn-action"><span class="turn-badge">${state.turns.length} / 6 speaking turns</span><button class="action-btn blue" data-news="log-reporter" ${expected?'':'disabled'}>${expected?'I asked this question →':'Wait for the expert’s answer'}</button></div><button class="text-switch" data-news="switch-expert">Switch to Expert View →</button></section></div>${after}`;
  }
  function factList(a){return `<dl class="fact-list"><div><dt>Animal</dt><dd>${esc(a.name)}</dd></div><div><dt>Found</dt><dd>${esc(a.found)}</dd></div><div><dt>Diet</dt><dd>${esc(a.diet)}</dd></div><div><dt>Special behavior</dt><dd>${esc(a.behavior)}</dd></div><div><dt>Threat</dt><dd>${esc(a.threat)}</dd></div><div><dt>Protection</dt><dd>${esc(a.protection)}</dd></div><div><dt>Interesting fact</dt><dd>${esc(a.fact)}</dd></div></dl>`}
  function expert(a){const expected=state.turns.length%2===1;return `<div class="news-layout"><section class="card news-visual expert-visual"><span class="role-pill expert-pill">STUDENT B · WILDLIFE EXPERT</span>${art()}<p class="mystery-caption">SECRET ANIMAL CARD · Keep this side away from the Reporter.</p></section><section class="card role-card expert-card"><div class="role-heading"><div><p class="overline">YOUR SECRET BRIEF</p><h3>${esc(a.name)}</h3></div>${timer()}</div>${factList(a)}<p class="overline">SAY IT WITH PASSIVE VOICE</p><div class="answer-frames">${answerList(a).map((x,i)=>`<button class="answer-frame ${state.selectedAnswer===i?'selected':''}" data-news="answer" data-i="${i}" aria-pressed="${state.selectedAnswer===i}">${esc(x)}</button>`).join('')}</div><div class="turn-action"><span class="turn-badge">${state.turns.length} / 6 speaking turns</span><button class="action-btn" data-news="log-expert" ${expected?'':'disabled'}>${expected?'I answered aloud →':'Wait for the reporter’s question'}</button></div><button class="text-switch" data-news="switch-reporter">Switch to Reporter View →</button></section></div>${state.revealed?sampleDialogue(a):''}`}
  function guessPanel(a){return `<section class="card guess-panel"><p class="overline">CASE FILE · GUESS THE ANIMAL</p><h3>${state.revealed?'Mystery solved!':'Make Your Guess'}</h3>${state.revealed?`<p class="guess-feedback right">Correct! It is a ${esc(a.name)}.</p>${sampleDialogue(a)}`:`<div class="guess-controls"><label for="animalGuess">Reporter, choose the animal:</label><select id="animalGuess"><option value="">Choose an animal</option>${animals.map((x,i)=>`<option value="${i}" ${state.guess===String(i)?'selected':''}>${esc(x.name)}</option>`).join('')}</select><button class="action-btn" data-news="guess">Make Your Guess</button></div><p class="guess-feedback" aria-live="polite">${state.guess&&!state.revealed?'Try Again — ask for another clue.':''}</p>`}</section>`}
  function render({teacher,projector}){window.teacher=teacher;const a=current();if(state.view==='transition')return `<section class="handoff" aria-live="polite"><span class="handoff-icon">↔</span><p class="overline">INFORMATION GAP · ROLE SWITCH</p><h3>Pass the screen to your partner.</h3><p>The next card is hidden until your partner is ready.</p><button class="action-btn" data-news="continue">${state.pending==='expert'?'I am the Expert · Show my card':'I am the Reporter · Show my prompts'}</button></section>`;return `<div class="newsroom ${projector?'newsroom-projector':''}"><div class="news-intro"><div><span class="pill">FINAL INTEGRATED SPEAKING TASK</span><h3>🕵️ Wildlife Mystery Newsroom</h3><p>Ask. Discover. Report.</p></div><div class="news-intro-side"><span>INFORMATION GAP · PAIR WORK</span><b>${state.turns.length} / 6 TURNS</b></div></div>${projector?reporter(a,true):state.view==='reporter'?reporter(a):expert(a)}${!projector&&teacher?teacherPanel():''}${!projector&&teacher&&state.sampleOpen?sampleDialogue(a):''}</div>`}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-news]');if(!b)return;const action=b.dataset.news,i=Number(b.dataset.i);if(action==='switch-expert')switchTo('expert');else if(action==='switch-reporter')switchTo('reporter');else if(action==='continue'){state.view=state.pending;window.render()}else if(action==='question'){state.selectedQuestion=i;window.render()}else if(action==='answer'){state.selectedAnswer=i;window.render()}else if(action==='log-reporter')logTurn('reporter');else if(action==='log-expert')logTurn('expert');else if(action==='guess'){const select=document.querySelector('#animalGuess');state.guess=select.value;if(state.guess===String(state.index))state.revealed=true;window.render()}else if(action==='reflect-q'||action==='reflect-p'){const set=action==='reflect-q'?state.reflectionQuestions:state.reflectionPassive;set.has(i)?set.delete(i):set.add(i);window.render()}else if(action==='random'){let n=Math.floor(Math.random()*(animals.length-1));if(n>=state.index)n++;reset(n)}else if(action==='next')reset((state.index+1)%animals.length);else if(action==='reset')reset();else if(action==='toggle-name'){state.nameRevealed=!state.nameRevealed;window.render()}else if(action==='toggle-facts'){state.factsRevealed=!state.factsRevealed;window.render()}else if(action==='toggle-sample'){state.sampleOpen=!state.sampleOpen;window.render()}else if(action==='large'){state.framesLarge=!state.framesLarge;window.render()}else if(action==='timer')startTimer();else if(action==='pair'){const names=state.roster.split(/[,，\n]+/).map(x=>x.trim()).filter(Boolean);if(names.length<2)state.pair='Enter at least two names.';else{const one=Math.floor(Math.random()*names.length);let two=Math.floor(Math.random()*(names.length-1));if(two>=one)two++;state.pair=`Reporter: ${names[one]} · Expert: ${names[two]}`}window.render()}});
  document.addEventListener('input',e=>{if(e.target.id==='rosterInput')state.roster=e.target.value});
  window.Newsroom={render,toProjector(){state.view='reporter';state.pending='expert'},getState:()=>({index:state.index,view:state.view,turns:state.turns.length,seconds:state.seconds,revealed:state.revealed})};
})();
